sentences = [
    # Group 1: Weather and Outdoors
    "The weather is lovely today.",
    "It's so sunny outside!",
    "The sky is clear and blue.",
    "A perfect day for a picnic.",
    "The sun is shining brightly.",
    "It's a warm and pleasant afternoon.",
    "The breeze is gentle and refreshing.",
    "The weather is ideal for a beach day.",
    "The day couldn't be more beautiful.",
    "I love these sunny days.",
    "The temperature is perfect for a walk.",
    "It's a wonderful day to be outside.",
    "The park looks stunning in this weather.",
    "What a glorious day!",
    "Today is a great day for outdoor activities.",
    "I can't get enough of this weather.",
    "It's an excellent day to go hiking.",
    "Such a bright and cheerful day!",
    "The sun feels warm on my skin.",
    "The weather couldn't be better.",
    "I wish every day could be this beautiful.",
    "It's the kind of day that lifts your spirits.",
    "A lovely day to enjoy nature.",
    "This weather is simply perfect.",
    "It's a beautiful morning.",
    "The sunset is going to be amazing tonight.",
    "Today is an ideal day for gardening.",
    "The sunlight is so invigorating.",
    "Such a calm and peaceful day.",
    "It's a great day for a bike ride.",
    
    # Group 2: Travel and Transport
    "He drove to the stadium.",
    "They took the bus to the city center.",
    "She enjoys long road trips.",
    "The train ride was smooth and fast.",
    "They traveled by plane to Europe.",
    "The taxi arrived promptly.",
    "He prefers to travel by bike.",
    "She commutes to work by subway.",
    "They love taking weekend trips.",
    "The journey was comfortable and quick.",
    "They rented a car for the trip.",
    "The flight was delayed by an hour.",
    "He likes exploring new cities by foot.",
    "They booked a cruise for their vacation.",
    "She travels for work frequently.",
    "He took the ferry to the island.",
    "They enjoyed the scenic drive.",
    "The travel experience was wonderful.",
    "She uses a ride-sharing app daily.",
    "They plan to travel around the world.",
    "He took a detour through the countryside.",
    "She packed her bags for the trip.",
    "They traveled light with just a backpack.",
    "The road was clear and traffic-free.",
    "He booked his tickets online.",
    "They had a layover in Paris.",
    "She prefers window seats on airplanes.",
    "They caught the last train home.",
    "He loves spontaneous road trips.",
    "The bus ride was bumpy but fun.",
    
    # Group 3: Reading and Books
    "She enjoys reading books on rainy days.",
    "He likes to read mystery novels.",
    "They have a large collection of books.",
    "She spends hours at the library.",
    "He reads every night before bed.",
    "They discuss books in their book club.",
    "She loves the smell of old books.",
    "He prefers physical books to e-books.",
    "They visit the bookstore every weekend.",
    "She reads a variety of genres.",
    "He enjoys reading biographies.",
    "They have a cozy reading nook.",
    "She reads while commuting.",
    "He finds reading very relaxing.",
    "They exchange books with friends.",
    "She loves finding new authors.",
    "He is always in the middle of a book.",
    "They enjoy reading together.",
    "She keeps a reading journal.",
    "He likes to read historical fiction.",
    "They read to their children every night.",
    "She has a list of must-read books.",
    "He enjoys visiting secondhand bookstores.",
    "They attend book signings and events.",
    "She loves rereading her favorite books.",
    "He reads newspapers every morning.",
    "They enjoy reading in the park.",
    "She collects rare and antique books.",
    "He prefers short stories and novellas.",
    "They enjoy reading aloud to each other.",
    
    # Group 4: Technology and AI
    "Artificial intelligence is transforming the world.",
    "He is fascinated by AI developments.",
    "She works in the tech industry.",
    "They discuss the future of technology.",
    "He reads about AI advancements daily.",
    "She is learning about machine learning.",
    "They believe AI will change many industries.",
    "He attends tech conferences regularly.",
    "She writes articles on AI and technology.",
    "They follow the latest tech news.",
    "He is interested in robotics.",
    "She enjoys coding and programming.",
    "They invest in tech startups.",
    "He uses AI tools in his work.",
    "She thinks AI can solve big problems.",
    "They are excited about smart home devices.",
    "He is studying data science.",
    "She believes in the potential of AI.",
    "They discuss ethical issues in AI.",
    "He is working on an AI project.",
    "She is taking an online course on AI.",
    "They think AI can improve healthcare.",
    "He reads books on AI and technology.",
    "She follows AI research closely.",
    "They are curious about AI applications.",
    "He uses AI for personal productivity.",
    "She is optimistic about AI's future.",
    "They think AI will create new jobs.",
    "He watches documentaries on technology.",
    "She believes AI will enhance education.",
    
    # Group 5: Animals and Pets
    "The cat sat on the mat.",
    "He loves playing with his dog.",
    "She has a pet parrot.",
    "They enjoy visiting the zoo.",
    "He feeds the birds in his garden.",
    "She volunteers at the animal shelter.",
    "They have a fish tank at home.",
    "He takes his dog for a walk daily.",
    "She loves watching wildlife documentaries.",
    "They adopted a stray cat.",
    "He is fascinated by marine life.",
    "She enjoys birdwatching.",
    "They have a small farm with animals.",
    "He likes learning about animal behavior.",
    "She is passionate about animal conservation.",
    "They support animal welfare organizations.",
    "He enjoys going on safaris.",
    "She has a pet rabbit.",
    "They visit animal sanctuaries.",
    "He likes taking photos of animals.",
    "She enjoys reading about different animals.",
    "They have a beehive in their garden.",
    "He is interested in veterinary science.",
    "She loves horseback riding.",
    "They keep chickens for fresh eggs.",
    "He has a collection of animal figurines.",
    "She enjoys watching animal rescue videos.",
    "They participate in wildlife surveys.",
    "He likes to draw animals.",
    "She enjoys writing stories about animals.",
    
    # Group 6: Hobbies and Interests
    "Programming can be both challenging and rewarding.",
    "He enjoys painting landscapes.",
    "She loves baking desserts.",
    "They are learning to play the guitar.",
    "He spends weekends gardening.",
    "She practices yoga every morning.",
    "They enjoy hiking in the mountains.",
    "He likes building model airplanes.",
    "She enjoys knitting and crocheting.",
    "They are members of a photography club.",
    "He is passionate about woodworking.",
    "She likes to sew her own clothes.",
    "They enjoy playing board games.",
    "He spends his free time fishing.",
    "She loves exploring new recipes.",
    "They enjoy doing puzzles together.",
    "He collects stamps from around the world.",
    "She takes dance classes.",
    "They enjoy going to art museums.",
    "He likes to write poetry.",
    "She is learning a new language.",
    "They enjoy volunteering in their community.",
    "He is interested in astronomy.",
    "She loves making jewelry.",
    "They enjoy camping trips.",
    "He likes to play chess.",
    "She enjoys scrapbooking.",
    "They are learning to scuba dive.",
    "He plays the piano.",
    "She enjoys flower arranging.",
    
    # Group 7: Music and Arts
    "Music has the power to heal and inspire.",
    "He enjoys listening to classical music.",
    "She loves attending live concerts.",
    "They play in a band together.",
    "He collects vinyl records.",
    "She enjoys singing in a choir.",
    "They go to music festivals.",
    "He likes composing his own songs.",
    "She is learning to play the violin.",
    "They enjoy dancing to their favorite tunes.",
    "He is a fan of jazz music.",
    "She enjoys playing the flute.",
    "They love exploring different music genres.",
    "He likes to write music reviews.",
    "She enjoys going to the opera.",
    "They have a home music studio.",
    "He is passionate about electronic music.",
    "She takes piano lessons.",
    "They enjoy watching musicals.",
    "He is interested in music production.",
    "She loves playing the guitar.",
    "They enjoy singing karaoke.",
    "He attends open mic nights.",
    "She is learning to play the drums.",
    "They enjoy creating playlists.",
    "He is a member of a music appreciation society.",
    "She likes writing song lyrics.",
    "They enjoy recording their music.",
    "He follows the latest music trends.",
    "She enjoys teaching music to children.",
    
    # Group 8: Phrases and Sayings
    "The quick brown fox jumps over the lazy dog.",
    "Actions speak louder than words.",
    "A picture is worth a thousand words.",
    "Better late than never.",
    "Curiosity killed the cat.",
    "Don't count your chickens before they hatch.",
    "Every cloud has a silver lining.",
    "Fortune favors the bold.",
    "Good things come to those who wait.",
    "Honesty is the best policy.",
    "If it ain't broke, don't fix it.",
    "Laughter is the best medicine.",
    "Necessity is the mother of invention.",
    "Practice makes perfect.",
    "The pen is mightier than the sword.",
    "When in Rome, do as the Romans do.",
    "You can't judge a book by its cover.",
    "A stitch in time saves nine.",
    "Beggars can't be choosers.",
    "Birds of a feather flock together.",
    "Cleanliness is next to godliness.",
    "Don't bite the hand that feeds you.",
    "Every rose has its thorn.",
    "Haste makes waste.",
    "Ignorance is bliss.",
    "Knowledge is power.",
    "Look before you leap.",
    "Money doesn't grow on trees.",
    "Old habits die hard.",
    "Practice what you preach.",
    
    # Group 9: Nature and Exploration
    "Exploring nature can be very relaxing.",
    "He loves hiking in the wilderness.",
    "She enjoys camping under the stars.",
    "They often go on nature walks.",
    "He is fascinated by wildlife.",
    "She enjoys birdwatching in the forest.",
    "They love to explore national parks.",
    "He likes to photograph landscapes.",
    "She enjoys kayaking on the lake.",
    "They go on nature retreats.",
    "He is interested in botany.",
    "She enjoys stargazing on clear nights.",
    "They love to visit botanical gardens.",
    "He enjoys rock climbing.",
    "She likes to meditate in nature.",
    "They participate in conservation efforts.",
    "He is passionate about environmentalism.",
    "She enjoys collecting natural artifacts.",
    "They like to explore caves.",
    "He enjoys mountain biking.",
    "She is interested in geology.",
    "They like to visit nature reserves.",
    "He enjoys fishing in the river.",
    "She likes to swim in natural springs.",
    "They often go on safari trips.",
    "He enjoys snorkeling in coral reefs.",
    "She likes to explore waterfalls.",
    "They enjoy trekking in the mountains.",
    "He likes to draw natural scenery.",
    "She enjoys writing about nature.",

    # Group 10: Health and Fitness
    "She enjoys going to the gym regularly.",
    "He likes running in the morning.",
    "They practice yoga for relaxation.",
    "She follows a healthy diet.",
    "He enjoys swimming laps in the pool.",
    "They participate in marathons.",
    "She loves cycling through the park.",
    "He does strength training exercises.",
    "They enjoy hiking on weekends.",
    "She takes a dance fitness class.",
    "He meditates to reduce stress.",
    "They enjoy playing tennis together.",
    "She attends a Pilates class.",
    "He follows a fitness routine.",
    "They go for a jog every evening.",
    "She enjoys group fitness sessions.",
    "He practices mindfulness daily.",
    "They have a personal trainer.",
    "She does home workouts.",
    "He loves rock climbing for fitness.",
    "They follow a wellness program.",
    "She attends Zumba classes.",
    "He enjoys practicing martial arts.",
    "They do stretching exercises every day.",
    "She prefers outdoor workouts.",
    "He monitors his fitness progress.",
    "They enjoy paddleboarding for exercise.",
    "She is training for a triathlon.",
    "He takes part in CrossFit sessions.",
    "They love practicing Tai Chi.",

    # Group 11: Food and Cooking
    "She loves trying new recipes.",
    "He enjoys cooking Italian cuisine.",
    "They like to bake together.",
    "She follows food blogs for inspiration.",
    "He enjoys grilling on weekends.",
    "They love exploring different cuisines.",
    "She takes cooking classes.",
    "He enjoys making homemade pizza.",
    "They love having dinner parties.",
    "She experiments with vegan recipes.",
    "He is passionate about gourmet cooking.",
    "They enjoy making desserts.",
    "She grows her own herbs.",
    "He likes to barbecue with friends.",
    "They enjoy food and wine pairings.",
    "She loves making healthy smoothies.",
    "He enjoys baking bread from scratch.",
    "They love dining out at new restaurants.",
    "She follows a gluten-free diet.",
    "He enjoys preparing seafood dishes.",
    "They love making sushi at home.",
    "She is learning to cook Thai food.",
    "He enjoys slow cooking recipes.",
    "They love hosting brunches.",
    "She likes making homemade pasta.",
    "He is interested in molecular gastronomy.",
    "They enjoy trying street food.",
    "She loves making festive holiday meals.",
    "He enjoys making sauces and condiments.",
    "They love cooking together as a family."
]

groups = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
    3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
    4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 
    7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 
    9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11
]

group_names = [
    "Weather and Outdoors",
    "Travel and Transport",
    "Reading and Books",
    "Technology and AI",
    "Animals and Pets",
    "Hobbies and Interests",
    "Music and Arts",
    "Phrases and Sayings",
    "Nature and Exploration",
    "Health and Fitness",
    "Food and Cooking"
]

